CREATE DATABASE mydatabase;
USE mydatabase;
DROP DATABASE mydatabase;
SHOW DATABASES;

CREATE TABLE STUDENT_TABLE
	(
	STUDENT_ID INT,
    STUDENT_NAME VARCHAR(100),
    COURSE_NAME VARCHAR(50)
    );
    
SHOW TABLES;
DESCRIBE STUDENT_TABLE;

ALTER TABLE STUDENT_TABLE ADD COLUMN EMAIL VARCHAR(50);

TRUNCATE TABLE STUDENT_TABLE;
DESC STUDENT_TABLE;

INSERT INTO STUDENT_TABLE VALUES(1,"MRUNAL","C001","mrunal@gmail.com");
INSERT INTO STUDENT_TABLE VALUES(2,"AASHU","C002","aashu@gmail.com");
INSERT INTO STUDENT_TABLE VALUES(4,"KUNAL","C004","kunal@gmail.com");

DELETE FROM STUDENT_TABLE;
select * from student_table;

SELECT * FROM STUDENT_TABLE WHERE COURSE_NAME <> "C001";

SELECT * FROM STUDENT_TABLE WHERE COURSE_NAME IN ("C001","C002");


CREATE TABLE STUDENT
	(	STUDENT_ID VARCHAR(20),
		NAME VARCHAR(20),
		COURSE_ID VARCHAR(20),
		DURATION INT(4)
	);
    

INSERT INTO student VALUES('1','ASIF',2,4);
INSERT INTO student VALUES('2','ATUL',1,4);
INSERT INTO student VALUES('1','ASIF',1,4);
INSERT INTO student VALUES(2,'ATUL',3,4);
INSERT INTO student VALUES(5,'JASMINE',1,4);
INSERT INTO student VALUES(6,'ADHITI',1,4);
    
SELECT *