-- CASE

SELECT * FROM employee_demographics;

SELECT FIRST_NAME,
LAST_NAME,
AGE,
CASE 
	WHEN AGE <=30 THEN 'YOUNG'
    WHEN AGE BETWEEN 31 AND 50 THEN 'OLD'
    WHEN AGE >= 50 THEN 'ON DEATHS DOOR'
END AS AGE_BRACKET
FROM EMPLOYEE_DEMOGRAPHICS; 
   
-- PAY INCREASE AND BONUS
-- < 50000 = 5%
-- > 50000 = 7%
-- FINANCE = 10% BONUS

SELECT FIRST_NAME, LAST_NAME, SALARY,
CASE
	WHEN SALARY < 50000 THEN SALARY + (SALARY * 0.05)
    WHEN SALARY > 50000 THEN SALARY + (SALARY * 0.07)
END AS NEW_SALARY,
CASE WHEN DEPT_ID = 6 THEN SALARY + 0.1
END AS BONUS
FROM EMPLOYEE_SALARY
ORDER BY NEW_SALARY DESC;

SELECT * 
FROM employee_salary;

SELECT * 
FROM parks_departments;