
SELECT GENDER, AVG(AGE)
FROM EMPLOYEE_DEMOGRAPHICS
GROUP BY GENDER;

/*
SELECT GENDER, AVG(AGE)
FROM employee_demographics
WHERE AVG(AGE) > 40							
GROUP BY GENDER							AGGREGATE FUNCTION AVG ONLY OCCURS AFTER GROUP BY IS DONE SO WHEN WE FILTER (WHERE)BASED ON AGGREGATE 
;										AVG AGE IT WONT WORK BECAUSE GROUP BY HASNT OCCURED YET		
*/
-- THATS WHY WE USE HAVING

SELECT OCCUPATION, AVG(SALARY) FROM 
EMPLOYEE_SALARY
WHERE OCCUPATION LIKE "%MANAGER"
GROUP BY OCCUPATION
HAVING AVG(SALARY) > 75000
;