-- TRIGGERS AND EVENTS

SELECT *
FROM EMPLOYEE_DEMOGRAPHICS;

SELECT * 
FROM EMPLOYEE_SALARY;

DELIMITER $$
CREATE TRIGGER EMPLOYEE_INSERT
	AFTER INSERT ON EMPLOYEE_SALARY
    FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_DEMOGRAPHICS (EMPLOYEE_ID, FIRST_NAME, LAST_NAME)
VALUES (NEW.EMPLOYEE_ID, NEW.FIRST_NAME, NEW.LAST_NAME);
END $$
DELIMITER ;

INSERT INTO EMPLOYEE_SALARY VALUES(13,'MRUNAL','SINGH','CEO',100000, NULL);