-- WINDOW FUNCTION

SELECT DEM.FIRST_NAME, DEM.LAST_NAME,GENDER, AVG(SALARY) AS AVG_salary
FROM EMPLOYEE_DEMOGRAPHICS DEM
JOIN employee_salary SAL
	ON DEM.EMPLOYEE_ID = SAL.employee_id
GROUP BY DEM.FIRST_NAME, DEM.LAST_NAME,GENDER;


SELECT DEM.FIRST_NAME, DEM.LAST_NAME, GENDER,SAL.SALARY,
AVG(SALARY) OVER(PARTITION BY GENDER) 
FROM EMPLOYEE_DEMOGRAPHICS DEM
JOIN employee_salary SAL
	ON DEM.EMPLOYEE_ID = SAL.employee_id;

-- ROW NUMBER

SELECT DEM.EMPLOYEE_ID, DEM.FIRST_NAME, DEM.LAST_NAME, GENDER, SAL.SALARY,
ROW_NUMBER() OVER()
FROM EMPLOYEE_DEMOGRAPHICS DEM
JOIN employee_salary SAL
	ON DEM.EMPLOYEE_ID = SAL.employee_id;

SELECT DEM.EMPLOYEE_ID, DEM.FIRST_NAME, DEM.LAST_NAME, GENDER, SAL.SALARY,
ROW_NUMBER() OVER(PARTITION BY GENDER ORDER BY SALARY DESC) AS ROW_NUM, 
RANK() OVER(PARTITION BY GENDER ORDER BY SALARY DESC) AS RANK_NUM,
DENSE_RANK() OVER(PARTITION BY GENDER ORDER BY SALARY DESC) AS DENSE_RANK_NUM
FROM EMPLOYEE_DEMOGRAPHICS DEM
JOIN employee_salary SAL
	ON DEM.EMPLOYEE_ID = SAL.employee_id;
